#!/usr/bin/python
# Usage: typeslots.py < Include/typeslots.h typeslots.inc

import sys, re


def generate_typeslots(out=sys.stdout):
    out.write("/* Generated by typeslots.py */\n")
    res = {}
    for line in sys.stdin:
        m = re.match("#define Py_([a-z_]+) ([0-9]+)", line)
        if not m:
            continue

        member = m.group(1)
        if member == "tp_token":
            # The heap type structure (ht_*) is an implementation detail;
            # the public slot for it has a familiar `tp_` prefix
            member = '{-1, offsetof(PyHeapTypeObject, ht_token), -1}'
        elif member in ('tp_base', 'tp_bases', 'tp_doc', 'tp_methods', 'tp_members'):
            member = f'{{-1, offsetof(PyTypeObject, {member}), -1}}'
        elif member.startswith("tp_"):
            member = f'{{-1, offsetof(PyTypeObject, {member}), offsetof(PyTypeObject, tp_functionflags[_PyFunctionIndex_{member}])}}'
        elif member.startswith("am_"):
            member = (f'{{offsetof(PyAsyncMethods, {member}),'+
                      f' offsetof(PyTypeObject, tp_as_async), offsetof(PyAsyncMethods, am_functionflags[_PyFunctionIndex_{member}])}}')
        elif member.startswith("nb_"):
            member = (f'{{offsetof(PyNumberMethods, {member}),'+
                      f' offsetof(PyTypeObject, tp_as_number), offsetof(PyNumberMethods, nb_functionflags[_PyFunctionIndex_{member}])}}')
        elif member.startswith("mp_"):
            member = (f'{{offsetof(PyMappingMethods, {member}),'+
                      f' offsetof(PyTypeObject, tp_as_mapping), offsetof(PyMappingMethods, mp_functionflags[_PyFunctionIndex_{member}])}}')
        elif member.startswith("sq_"):
            member = (f'{{offsetof(PySequenceMethods, {member}),'+
                      f' offsetof(PyTypeObject, tp_as_sequence), offsetof(PySequenceMethods, sq_functionflags[_PyFunctionIndex_{member}])}}')
        elif member.startswith("bf_"):
            member = (f'{{offsetof(PyBufferProcs, {member}),'+
                      f' offsetof(PyTypeObject, tp_as_buffer), offsetof(PyBufferProcs, bf_functionflags[_PyFunctionIndex_{member}])}}')
        res[int(m.group(2))] = member

    M = max(res.keys())+1
    for i in range(1,M):
        if i in res:
            out.write("%s,\n" % res[i])
        else:
            out.write("{0, 0},\n")


def main():
    if len(sys.argv) == 2:
        with open(sys.argv[1], "w") as f:
            generate_typeslots(f)
    else:
        generate_typeslots()

if __name__ == "__main__":
    main()
